services:
  api:
    image: ghcr.io/metube-org/metube-backend:main
    ports:
      - 32500:32500
    environment:
      ENVIRONMENT_NAME: local
      MONGODB_CONECTION_URL: mongodb://root:example@0.0.0.0:27017/
    restart: always
  mongo:
    image: mongo:5.0.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-admin-ui:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@0.0.0.0:27017/
      ME_CONFIG_BASICAUTH_USERNAME: unibuc
      ME_CONFIG_BASICAUTH_PASSWORD: adobe